### ISSUE TITLE
This documentation need to be clarified.. I read it 5 times still don't understand how to use it..

### ISSUE THREAD

**Issue by richardsondx** [kuflash/react-router-sitemap#42]
"It's a minimal example. After running the script, a sitemap.xml file will be created, which includes all paths, described in the configuration of react-router."

1. You're not explaining which script so I had to guess that it was sitemap-builder.js
2. You're not saying how to 'run' the script..  
3. It's not clear what's the purpose of your 'API'.

**Comment by kuflash** [comment]
@richardsondx thank you for feedback! You're right, need run `./example/sitemap-builder.js` for build example sitemap. The script is run with the help of Node.js in your terminal:
```
node ./example/sitemap-builder.js
```

Also your can define npm command in your package.json in `scripts` area:

```json
"scripts": {
    "build:sitemap": "node ./example/sitemap-builder.js",
  },
```

and run 
```
npm run build:sitemap
```

I tried to make the library more modular, so that everyone can build your way to the sitemap generation without the use of my constructor `new Sitemap(router)`. I created 3 independent functions that can be applied separately and create your API to generate sitemap:
1. [routesParser](https://github.com/kuflash/react-router-sitemap/blob/master/api.md#routesparser) - transform react-router config to array of paths
2. [pathsFilter](https://github.com/kuflash/react-router-sitemap/blob/master/api.md#pathsfilter) - can filter some paths
3. [paramsApplier](https://github.com/kuflash/react-router-sitemap/blob/master/api.md#paramsapplier) - can generate dynamic paths by params

**Comment by richardsondx** [comment]
Hey @kuflash I really appreciate you took the time to answer and clarify your documentation a little bit. I really want to use this tool, it looks very useful. Thanks,  I figured out some of the steps already for running the commands ( :) I was ready to submit a pull request to your documentat)  but I'm running into some issue when I set the path to my `router.jsx` file.

For some reason its complaining about the if statement in my router file when I run the script.

```
SyntaxError: /Users/richardson/Code/React/reater-new-frontend/routes/routes.jsx: Unexpected token (11:15)
   9 | if (typeof window === 'object') {
  10 |     function createElement(Component, props) {
> 11 |         return <Component {...props} custom={window.PROPS} />;
     |                ^
  12 |     }
  13 | }
  14 |
    at Parser.pp$5.raise (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp$3.parseExprAtom (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3670:12)
    at Parser.pp$3.parseExprSubscripts (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$3.parseExpression (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:3226:19)
    at Parser.pp$1.parseReturnStatement (/Users/richardson/Code/React/reater-new-frontend/node_modules/babylon/lib/index.js:2024:26)
```

**Comment by kuflash** [comment]
@richardsondx maybe you need import `babel-register` in your sitemap builder script? Like [here](https://github.com/kuflash/react-router-sitemap/blob/master/example/sitemap-builder.js#L1). And you need create [.babelrc](https://github.com/kuflash/react-router-sitemap/blob/master/.babelrc) file in root your project.

**Comment by edwardbiden** [comment]
I'm seeing a similar problem (after creating .babelrc as in the link): 

`/Users/edwardbiden/Code/learnitect-react/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/edwardbiden/Code/learnitect-react/src/tools/router.jsx: Unexpected token (5:2)
  3 | 
  4 | export default (
> 5 |   <Route>
    |   ^
  6 |     <Route exact path="/" />
  7 |     <Route path="/graduates" />
  8 |     <Route path="/team-leads" />
    at Parser.pp$5.raise (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/Users/edwardbiden/Code/learnitect-react/node_modules/babylon/lib/index.js:3709:19)`

Do you know what the problem is?

**Comment by kuflash** [comment]
@edwardbiden did you install dependencies Babel Preset for React? Judging by mistake, you do not support the JSX syntax. Can you show me file where you import `react-router-sitemap`?

**Comment by edwardbiden** [comment]
Ok, really appreciate your help on this. The instructions are also not so clear to me, but I'm just teaching myself React the past few weeks, so I thought that was just me ... ;-)

So, I copied these lines into my App.js file:
```
import "babel-register";
import Sitemap from 'react-router-sitemap';

const router = require('./tools/router').default;

new Sitemap(router)
.build('http://my-site.ru')
.save('./sitemap.xml');
```
My site-builder.js file looks like this:
```
require('babel-register');
require('react-router-sitemap');

const router = require('./router').default;
const Sitemap = require('../').default;

(
    new Sitemap(router)
        .build('https://learnitect.com')
        .save('../sitemap.xml')
);
```
And my router.js file looks like this:
```
import React from 'react';
import { Route } from 'react-router';

export default (
  <Route>
      <Route exact path="/" />
      <Route path="/graduates" />
      <Route path="/team-leads"/>
      <Route path="/associate-programme"/>
      <Route path="/boot-camp" />
      <Route path="/fast-track-scheme"/>
      <Route path="/leadership-programme" />
      <Route path="/companies"  />
      <Route path="/about"  />
      <Route path="/contact" />
  </Route>
);
```
(This is duplicate code from App.js where I have some <Router> code mixed in with GA and Hubspot tracking, to make things simpler. It's a bit confusing for me all the different Router / Route / router / etc. things that you are referring too - I created a new router.js to prevent duplicate declarations)

I build locally as normal:
```
npm start
```

The terminal looks good, but in the browser, instead of seeing the site I see this error:
```
TypeError: d.default.writeFileSync is not a function
(anonymous function)
node_modules/react-router-sitemap/index.es5.js:1
```
and it points to the line in App.js:
```
new Sitemap(router)
```

It's a different error from last time... I'll keep playing around with it, but any help would be great. Thanks for the quick response last time.

**Comment by edwardbiden** [comment]
I tried it slightly differently too... removed everything from App.js and created a new folder in my project "/tools" and then added two files: router.jsx and sitemap-builder.js

router.jsx
```
import React from 'react';
import { Route, Redirect } from 'react-router';

export default (
	<Route>
		<Route path='/' />
		<Route path='/about' />
		<Route path='/projects'>
			<Route path=':projectName'>
				<Route path='view' />
			</Route>
		</Route>
		<Route path='/contacts' />
		<Route path='/auth' />
		<Redirect from='/home' to='/' />
		<Route path='*' />
	</Route>
);
```

sitemap-builder.js:
```
require('babel-register');

const router = require('./router').default;
const Sitemap = require('../').default;

(
	new Sitemap(router)
		.build('http://my-site.ru')
		.save('./sitemap.xml', '/static/')
);
```

and then I tried it via terminal, as I read the browser might be causing the writeFileSync error I was getting before.
```
node sitemap-builder
```
So my files are exactly what is in the documentation, but I get this error:
```
Edwards-MacBook-Pro:tools edwardbiden
/Users/edwardbiden/Code/learnitect-react/node_modules/bootstrap/dist/css/bootstrap.css:7
html {
     ^
SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/edwardbiden/Code/learnitect-react/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

.babelrc looks like this:
```
{
	"ignore": [
		"node_modules/**/*"
	],
	"presets": [
		"es2015",
		"react"
	]
}
```

and to install babel presets I ran: 
```
npm install --save-dev babel-preset-es2015
```

but still not working

**Comment by kuflash** [comment]
@edwardbiden you need add this is code into `sitemap-builder.js`:
```js
require.extensions['.css'] = function () {
  return null;
};
```

**Comment by edwardbiden** [comment]
this now gives the following error:
```
Edwards-MacBook-Pro:tools edwardbiden$ node sitemap-builder
/Users/edwardbiden/Code/learnitect-react/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/edwardbiden/Code/learnitect-react/src/assets/logos/hrreview.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | 
  3 | 
```

**Comment by kuflash** [comment]
@edwardbiden you need add this is construction for all non-JS resources. For example:
require.extensions['.css', '.png'] = function () {
  return null;
};

**Comment by edwardbiden** [comment]
@kuflash ok awesome - thanks I got this going now :-)

I realised as well, that because I installed react-router-sitemap from npm, that the folder structure in my project is not exactly the same as in github here. Just in case anyone else is having the same problem I'll explain what I did... 

First I added the constructor for all non-JS resources as you suggest:
```
require.extensions['.css', '.png', '.jpeg', '.jpg'] = function () {
  return null;
};
```

Then I needed to change the line importing react-router-sitemap from this:
```
const Sitemap = require('../').default;
```
To this:
```
const Sitemap = require('./node_modules/react-router-sitemap').default;
```
I think this what you were telling me in an earlier comment when you asked where I imported react-router-sitemap, but I only just figured it out. Here's the full code for my sitemap-builder.js:
```
require('babel-register');

require.extensions['.css', '.png', '.jpeg', '.jpg'] = function () {
  return null;
};

const router = require('./router').default;
const Sitemap = require('./node_modules/react-router-sitemap').default;

(
	new Sitemap(router)
		.build('http://my-site.ru')
		.save('./sitemap.xml')
);
```

Thanks for all your help - really appreciate it!

**Comment by kuflash** [comment]
You not need write full path to `node_modules` for import `react-router-sitemap`. It is enough to write so:
```js
const Sitemap = require('react-router-sitemap').default;
```

**Comment by abhijain2003** [comment]
![gn](https://user-images.githubusercontent.com/91718608/171394800-937928ad-8498-489b-aa71-b571c3878334.png)
![Screenshot 2022-06-01 170338](https://user-images.githubusercontent.com/91718608/171394805-7610c144-0218-4bf7-b2c5-ffc835767a0e.png)
![Screenshot 2022-06-01 170357](https://user-images.githubusercontent.com/91718608/171394807-38e00c59-e0e6-4536-84e0-39a8fc305c88.png)
![Screenshot 2022-06-01 170414](https://user-images.githubusercontent.com/91718608/171394809-e4047150-cbfb-4c78-92cd-729f96517138.png)


I am building a blog website where i am fetching data from my API you can see on picture
I am running react-router-sitemap and I did exactly same as mentioned in above chat. still I got this error of unexpected token 

help me resolving this please
