### ISSUE TITLE
react-router-sitemap creates 2 files: sitemap.xml and sitemap-0.xml

### ISSUE THREAD

**Issue by immunity20** [kuflash/react-router-sitemap#72]
Hello, my router is 🥇 
```
<Router>
<Route path="/" component={App}>
      <IndexRoute component={Home} />
      <Route
        path="/aboutus"
        component={AboutUs}
      />
      <Route
        path="/account"
        component={Profile}
      />
</Route>
</Router>
```

sitemap creates 2 files sitemap.xml ( only contains /) and sitemap-0.xml (contains the rest paths).

**Comment by kuflash** [comment]
Hi @immunity20. Can you show your xml files?
Now, package generate 2 files, because we need support long sitemaps. First file storing links on sitemap chunks with [max URLs](https://www.microsystools.com/products/sitemap-generator/help/xml-sitemaps-page-limit/). 

It is possible of course to write a condition that will check the maximum number of URLs and decide to create several files or one. I will try to implement this in the near future.

**Comment by kuflash** [comment]
@immunity20 it's fixed by @daijobou3. I'm publish version 1.1.4 in npm with this is fix
